-- Script para correção do banco de dados
-- Necessário para permitir operações de "Entrada" (sem origem) e "Saída" (sem destino).

-- Alterar a tabela MOVIMENTACAO_ALMOXARIFADO para permitir NULL nas colunas de origem e destino
ALTER TABLE MOVIMENTACAO_ALMOXARIFADO MODIFY COLUMN IDALMOX_ORIGEM INT NULL;
ALTER TABLE MOVIMENTACAO_ALMOXARIFADO MODIFY COLUMN IDLOTE_ORIGEM INT NULL;
ALTER TABLE MOVIMENTACAO_ALMOXARIFADO MODIFY COLUMN IDALMOX_DESTINO INT NULL;
ALTER TABLE MOVIMENTACAO_ALMOXARIFADO MODIFY COLUMN IDLOTE_DESTINO INT NULL;

-- Caso esteja usando um banco diferente de MySQL (ex: PostgreSQL), o comando seria:
-- ALTER TABLE MOVIMENTACAO_ALMOXARIFADO ALTER COLUMN IDALMOX_ORIGEM DROP NOT NULL;
-- ALTER TABLE MOVIMENTACAO_ALMOXARIFADO ALTER COLUMN IDLOTE_ORIGEM DROP NOT NULL;
-- ALTER TABLE MOVIMENTACAO_ALMOXARIFADO ALTER COLUMN IDALMOX_DESTINO DROP NOT NULL;
-- ALTER TABLE MOVIMENTACAO_ALMOXARIFADO ALTER COLUMN IDLOTE_DESTINO DROP NOT NULL;
